Import( 'env' )
Import( 'compmap' )
import profiles

profiles.make_rpal_master( env )
profiles.Program(
        'rpHostCommonPlatformExe',
        profiles.RpalModule()
        ).Target(
            env,
            'main.c',
            compmap,
            'rpHostCommonPlatformLib'
            )

# EOF
